.TH TESTPING 1 "Januar 2024" "Version 1.0" "testping Manual"

.SH NAME
testping \- Dienstprogramm zum gleichzeitigen Pingen mehrerer Hosts und zur Verwaltung von Konfigurationen

.SH SYNOPSIS
.B testping
[\fIOPTION\fR]

.SH BESCHREIBUNG
Das \fBtestping\fR-Skript ermöglicht das gleichzeitige Pingen mehrerer Hosts, das Bearbeiten von Konfigurationen und die Verwaltung einer Liste von Hosts. Es bietet auch Optionen zum Installieren und Deinstallieren eines Cron-Jobs für periodisches Pingen.

.SH OPTIONEN
.TP
\fBconfig\fR
Bearbeiten Sie die Konfigurationsdatei mit dem nano-Editor.
.TP
\fBaddhost [IP]\fR
Fügt einen Host zur Liste der zu pingenden Hosts hinzu.
.TP
\fBdelhost [IP]\fR
Entfernt einen Host aus der Liste der Hosts.
.TP
\fBhosts\fR
Zeigt die Liste der gespeicherten Hosts an.
.TP
\fB-h\fR
Zeigt diese Hilfemeldung an.
.TP
\fBinstall [MINUTEN]\fR
Installiert einen Cron-Job, um das testping-Skript regelmäßig auszuführen. Der Cron-Job wird alle angegebenen Minuten ausgeführt.
.TP
\fBuninstall\fR
Deinstalliert den Cron-Job.
.TP
\fBprintlog\fR
Zeigt Protokolle von nicht erreichbaren Hosts an.
.TP
(Keine Option)
Führt Ping-Tests für alle Hosts in der Liste durch.
.SH BEISPIELE
.B testping
Führt Ping-Tests für alle Hosts in der Liste durch.
.BR
.B testping config
Bearbeitet die Konfigurationsdatei.
.BR
.B testping addhost 192.168.1.1
Fügt den Host 192.168.1.1 zur Liste hinzu.
.BR
.B testping delhost 192.168.1.1
Entfernt den Host 192.168.1.1 aus der Liste.
.BR
.B testping hosts
Zeigt die Liste der gespeicherten Hosts an.
.BR
.B testping -h
Zeigt Hilfeinformationen an.
.BR
.B testping install 5
Installiert einen Cron-Job, um das Skript alle 5 Minuten auszuführen.
.BR
.B testping uninstall
Deinstalliert den Cron-Job.
.BR
.B testping printlog
Zeigt Protokolle von nicht erreichbaren Hosts an.
.SH DATEIEN
\fB/usr/share/testping/config.cfg\fR
Konfigurationsdatei für testping.
.BR
\fB/usr/share/testping/hosts\fR
Datei mit einer Liste von Hosts.
.BR
\fB/usr/share/testping/log.txt\fR
Protokolldatei für nicht erreichbare Hosts.
.SH AUTOR
Geschrieben von Sebastian Falter.


.SH URHEBERRECHT
Dieses Skript wird unter der MIT-Lizenz veröffentlicht.
