.TH testping 1 "Dezember 2023" "1.0" "testping man page"

.SH NAME
testping \- Ein Skript zur Durchführung von Pings und Verwaltung von Hosts

.SH BESCHREIBUNG
Das testping-Skript ermöglicht das Durchführen von Ping-Operationen und die Verwaltung von Hosts. Es bietet folgende Funktionen:

.SH SYNTAX
.B testping
[\fIOPTION\fR]

.SH OPTIONEN
.TP
.B config
Öffnet die Konfigurationsdatei für testping zur Bearbeitung.

.TP
.B addhost \fIIP_ADDRESS\fR
Fügt eine IP-Adresse zur Liste der Hosts hinzu.

.TP
.B delhost \fIIP_ADDRESS\fR
Entfernt eine IP-Adresse aus der Liste der Hosts.

.TP
.B hosts
Zeigt die gespeicherten Hosts an.

.TP
.B install \fIMINUTES\fR
Installiert einen Cron-Job, um das testping-Skript alle \fIMINUTES\fR Minuten auszuführen.

.TP
.B uninstall
Deinstalliert den Cron-Job für das testping-Skript.

.SH BEISPIELE
Das Skript testping kann folgendermaßen verwendet werden:

.B testping config
.BR
.B testping addhost 192.168.1.1
.BR
.B testping delhost 192.168.1.1
.BR
.B testping hosts
.BR
.B testping install 5
.BR
.B testping uninstall


.SH AUTOR
Autor Sebastian Falter

.SH VERSION
1.0

.SH SIEHE AUCH
ping(8)

.SH BUGS
Keine bekannten Bugs.

.SH COPYRIGHT
Dies ist ein frei verfügbares Skript; Es gibt keine Lizenzbeschränkungen.

.SH HINWEISE
Dieses Skript wird ohne jegliche Garantie zur Verfügung gestellt.

